appName: demo-app
appUniqueId: ravis/demo-app
appInfo:
  description: this is demo app
  appVersion: 1.0.0
  appRepoUrl: https://github.com/rawatSingh2022/demo-app.git
  appIconUrl: ''
  appAuthorUserId: ravis
  forkedFrom: ''
technicalInfo:
  supportedLanguages: []
  supportedFrameworks: []
  secrets: []
  services: []
  knowledgebases: []
  instruction: []
usage:
  develop:
    run: []
    agents: []
    layout: ''
  install:
    steps: []
    customInstallationAgent:
      enabled: false
      agent: ''
  appUse:
    prerunsteps: []
    agents: []
    layout: ''
    appPreview:
      type: ''
